# Generated by Django 5.2.5 on 2025-08-14 10:25

from decimal import Decimal

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fbomatic", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="refueling",
            name="price",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                max_digits=5,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("1"))],
            ),
        ),
        migrations.AddConstraint(
            model_name="refueling",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("price__isnull", True), models.Q(("aircraft__isnull", True), ("quantity__lt", 0)), _connector="OR"
                ),
                name="give_or_take",
            ),
        ),
    ]
