# Generated by Django 5.2.5 on 2025-08-13 10:07

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Aircraft",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("registration", models.CharField(max_length=16, unique=True)),
            ],
            options={
                "verbose_name_plural": "aircraft",
                "ordering": ("registration",),
            },
        ),
        migrations.CreateModel(
            name="Pump",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
                ("capacity", models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ("counter", models.PositiveIntegerField()),
                ("remaining", models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Refueling",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("counter", models.PositiveIntegerField()),
                ("remaining", models.PositiveIntegerField()),
                ("quantity", models.IntegerField()),
                (
                    "aircraft",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to="fbomatic.aircraft"
                    ),
                ),
                ("pump", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="fbomatic.pump")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "ordering": ("-timestamp",),
            },
        ),
    ]
