# Generated by Django 5.2.5 on 2025-08-14 11:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("fbomatic", "0002_refueling_price_refueling_give_or_take"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="refueling",
            name="remaining",
        ),
    ]
