# Generated by Django 5.2.5 on 2025-08-15 12:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fbomatic", "0003_remove_refueling_remaining"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="pump",
            constraint=models.CheckConstraint(
                condition=models.Q(("remaining__lte", models.F("capacity"))), name="remaining_lte_capacity"
            ),
        ),
    ]
