# Generated by Django 5.2.5 on 2025-09-11 06:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fbomatic", "0004_pump_remaining_lte_capacity"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="aircraft",
            options={"ordering": ("priority", "registration"), "verbose_name_plural": "aircraft"},
        ),
        migrations.AddField(
            model_name="aircraft",
            name="priority",
            field=models.PositiveIntegerField(default=1000),
        ),
    ]
