# Generated by Django 5.2.5 on 2025-09-11 06:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("fbomatic", "0005_alter_aircraft_options_aircraft_priority"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="aircraft",
            options={"ordering": ("-priority", "registration"), "verbose_name_plural": "aircraft"},
        ),
    ]
