name: CI
on: [ push ]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    strategy:
      fail-fast: false
      matrix:
        python-version:
          - "3.12"
          - "3.13"

    env:
      DJANGO_DEBUG: "1"

    steps:
      - run: sudo apt-get install -y gettext

      - uses: actions/checkout@v5

      - uses: astral-sh/setup-uv@v6
        with:
          python-version: ${{ matrix.python-version }}

      - run: uv sync --dev

      - run: uv run ruff check

      - run: uv run ruff format --diff

      - run: uv run python src/manage.py makemigrations --check

      - run: uv run python src/manage.py compilemessages

      - run: uv run pytest --cov --cov-fail-under=95
